name: AI Code Review
on:
  pull_request:
    types: [opened, synchronize] # triggers on new PR and each commit

jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:

      - name: Run AI Reviewer
        uses: propstreet/reviewer@v2
        with:
          azureOpenAIKey: ${{ secrets.AZURE_PR_AI_OPENAI_API_KEY }}
          azureOpenAIEndpoint: ${{ secrets.AZURE_PR_AI_OPENAI_REASONING_ENDPOINT }}
          azureOpenAIDeployment: ${{ secrets.AZURE_PR_AI_OPENAI_REASONING_DEPLOYMENT }}
          azureOpenAIVersion: ${{ secrets.AZURE_PR_AI_OPENAI_REASONING_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
